PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: job
DROP TABLE IF EXISTS job;
CREATE TABLE job (ID integer NOT NULL,	USER_ID integer NOT NULL,TITLE varchar(100),DESCRIPTION varchar(4000),COUNTRY_ID integer,TOWN_ID integer,PROVINCE_ID integer,IS_OFFER integer NOT NULL,IS_ACTIVE integer,PAYMENT_MODE varchar(1),AMOUNT integer,DATE_CREATED integer,DATE_MODIFIED integer,DATE_DELETED integer,PRIMARY KEY (ID));
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (0, 4, 'Oferta juan 1a', 'fontanero', 0, 962, 48, 0, 1, 'H', 66, '2015-07-09 15:03:59');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (1, 3, 'asdf', 'asdfsadf', 0, 198, 4, 1, 1, 'H', 11, '2015-06-07 08:41:33');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (2, 3, 'Fontanero', 'Fontanero con experiencia', 0, 8, 8, 1, 1, 'H', 11, '2015-06-07 13:21:57');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (3, 3, 'Mecanico', 'mecanico por horas', 0, 8, 8, 1, 1, 'D', 110, '2015-06-07 13:22:57');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (4, 3, 'Electricista', 'especilista en instalacion', 0, 8, 8, 1, 1, 'J', 110, '2015-06-07 13:23:37');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (5, 3, 'Programador', 'programador java', 0, 8, 8, 1, 1, 'C', 111, '2015-06-07 13:26:22');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (6, 4, 'Oferta juan 009', 'fontanero', 0, 962, 48, 0, 1, 'J', 66, '2015-07-13 11:26:58');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (7, 4, 'Oferta juan 2', 'electricista', 0, 962, 48, 1, 1, 'H', 12, '2015-06-08 12:47:50');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (8, 4, 'Demanda juan 1a', 'busco panadero', 0, 962, 48, 0, 1, 'H', 12, '2015-07-09 15:12:59');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (9, 4, 'Demanda juan 2', 'busco mecanico', 0, 962, 48, 1, 1, 'H', 12, '2015-06-08 12:49:01');
INSERT INTO job (ID, USER_ID, TITLE, DESCRIPTION, COUNTRY_ID, TOWN_ID, PROVINCE_ID, IS_OFFER, IS_ACTIVE, PAYMENT_MODE, AMOUNT, DATE_CREATED) VALUES (10, 4, 'sadf', 'asdf', 0, 149, 2, 1, 1, 'H', 0, '2015-06-08 13:33:55');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;